### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SneakyWhoami** [movaid7/DarthInvaders#1]
This is really great. Could you please specify the use/redistribution/modification rights? Thanks in advance!

**Comment by movaid7** [comment]
Hey @SneakyWhoami 

I went ahead and added an MIT License: #2
Hope it's useful for whatever you're trying to do! Just be wary of the (very likely) spaghetti code in this repo😅

I had no idea anyone would find this code useful. It was just a silly game we made on campus as part of a project.
